### ISSUE TITLE
Source LLMs

### ISSUE THREAD

**Issue by YongLD** [Eladlev/AutoPrompt#40]
Can this project use the source LLM? Such as Xcomposer or LLama? Have you test these LLMs in paper?

**Comment by jzyxn** [comment]
How to use local LLMs?

**Comment by Eladlev** [comment]
You should change in the relevant config file:
```
    method: 'llm'
    config:
        llm:
            type: 'HuggingFacePipeline'
            name: <The name of the model>
            max_new_tokens: <max tokens>
```

If you want also that the optimizer will be local (highly not recommended), then you should change the meta prompts folder to:
```
meta_prompts:
    folder: 'prompts/meta_prompts_completion'
```
